// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NMPortfolioServer.Models;

#nullable disable

namespace NMPortfolioServer.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20250517200649_PortfolioEntries")]
    partial class PortfolioEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NMPortfolioServer.Models.PortfolioEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LongDescriptionType")
                        .HasColumnType("int");

                    b.Property<string>("LongTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioEntries");
                });

            modelBuilder.Entity("NMPortfolioServer.Models.PortfolioThumbnailCarouselEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioEntryId");

                    b.ToTable("PortfolioThumbnailCarouselEntries");
                });

            modelBuilder.Entity("NMPortfolioServer.Models.PortfolioThumbnailCarouselEntry", b =>
                {
                    b.HasOne("NMPortfolioServer.Models.PortfolioEntry", null)
                        .WithMany("ThumbnailCarouselEntries")
                        .HasForeignKey("PortfolioEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NMPortfolioServer.Models.PortfolioEntry", b =>
                {
                    b.Navigation("ThumbnailCarouselEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
